name: CMake Test 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config libgtk-3-dev libvte-2.91-dev libgtksourceview-4-dev

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install -y pkgconfiglite
        choco install -y gtksourceview

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build project
      working-directory: build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Run tests (if any)
      working-directory: build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
