name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          pkg-config \
          libgtk-3-dev \
          libvte-2.91-dev \
          libgtksourceview-4-dev

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build project
      working-directory: build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}

    - name: Run tests (optional)
      working-directory: build
      run: |
        if [ -f "CTestTestfile.cmake" ]; then
          ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
        fi
